nome = str(input('Digite o seu nome: '))
nome1 = nome.upper()
print ('Seu nome com tudo maiúsculo: {}'.format(nome1))
nome2 = nome.lower()
print ('Seu nome com tudo minúsculo: {}'.format(nome2))
nome3 = nome.replace(' ','')
nome4 = len(nome3)
print ('O nome possui {} letras'.format(nome4))
nome5 = nome.split()
nome6 = len(nome5[0])
print ('O primeiro nome possui {} letras'.format(nome6))